sovity/edc-ce

README.md
resources/docs/docker-compose.yml

Make the dev environment the default by updating the documentation and urls in docker-compose.
- closes https://github.com/sovity/edc-extensions/issues/8

chore: set dev as default environment (in docs and docker-compose)

---

extensions/catalog-transfer-extension/src/main/java/sender/RegisterConnectorRequestSender.java

Previously the connector wasnt being registered due to a null pointer exception. This fix adds the missing field that caused the exception.  Since the connector is now being registered to the broker this fixes the problem that title, maintainer and curator weren't being updated. 
I tested this with a custom run configuration.
- fixes https://github.com/sovity/edc-extensions/issues/9

fix: connector not registering to broker due to null pointer exception

---

extensions/broker/src/main/java/de/sovity/extension/broker/BrokerExtension.java
extensions/broker/src/main/java/de/sovity/extension/broker/sender/UnregisterConnectorRequestSender.java
extensions/broker/src/main/java/de/sovity/extension/broker/sender/message/UnregisterConnectorMessage.java
extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java

This PR implements necessary classes and methods to unregister a connector at the broker. 
Conveniently enough, unregistering the connector also unregisters the resources. 
I tested this with the test broker and run configuration. On graceful shutdown (exit in intellij, not stop) the connector gets unregistered and the resources also disappear from the broker.
- closes https://github.com/sovity/edc-extensions/issues/41

feat: unregister connector on shutdown

---

resources/docs/get_client.sh

Adds support for newer openssl versions
Tested locally with version 1.1.1. Couldnt test with newer version.
-   closes https://github.com/sovity/edc-extensions/issues/62

chore: add support for newer openssl versions to get_client script

---

resources/docs/postman_collection.json

The Postman Collection ports were outdated due to changes in the docker-compose.
Closes #88

fix: update ports of postman_collection.json

---

extensions/last-commit-info/src/test/java/de/sovity/edc/extension/version/controller/LastCommitInfoEnvTest.java
extensions/last-commit-info/src/test/java/de/sovity/edc/extension/version/controller/LastCommitInfoJarTest.java

Fixes last-commit-info-Extension tests are failing.
Closes #132

fix: last-commit-info-Extension tests are failing

---

extensions/last-commit-info/README.md
extensions/policy-always-true/README.md

The README.md changes in full view are:
https://github.com/sovity/edc-extensions/tree/2023-03-02-fix-last-commit-info-readme/extensions/last-commit-info
https://github.com/sovity/edc-extensions/tree/2023-03-02-fix-last-commit-info-readme/extensions/policy-always-true

add README.md to last commit info extension

---

extensions/postgres-flyway/src/main/java/de/sovity/edc/extension/postgresql/PostgresFlywayExtension.java
extensions/postgres-flyway/src/main/java/de/sovity/edc/extension/postgresql/migration/FlywayService.java

Add possibility to flyway repair when migrations failed. Setting `edc.flyway.repair` controls, if the repair is executed when a migration fails.
- With uninitialized database
- With adapted migration scripts, which need to trigger repair
- With an up-to-date database state

feat: Add possibility to flyway repair when migrations failed

---

docker-compose.yaml

Sets the used version to the last version (as desired).

chore: set tagged version in docker-compose to latest release

---

CHANGELOG.md
extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java

Under certain circumstances the broker returns too many resources after execution of the SPARQL query, even those that do not belong to the connector itself given his hostname. These are filtered out herewith.

refactor: add subsequent resource id filtering after sparql query

---

.env
connector/.env
connector/Dockerfile
docker-compose-dev.yaml

EDC_VAULT file is required, although its contents are optional.
The file is now added in Dockerfile, the property referring to it is added in the .env file, keeping the docker-composes clean.

fix empty EDC_VAULT file required error

---

.env

Switches 
`RELEASE_EDC_IMAGE=ghcr.io/sovity/edc-mds:3.0.0` (not working)
to
`RELEASE_EDC_IMAGE=ghcr.io/sovity/edc-ce-mds:3.0.0`

fix: env release edc image

---

extensions/wrapper/wrapper-broker-api/build.gradle.kts
extensions/wrapper/wrapper-common-api/build.gradle.kts
extensions/wrapper/wrapper-ee-api/build.gradle.kts

it was causing WARNINGS when importing those JARs, as you had the code, but not the libraries for the annotations

fix swagger annotations missing in api jars

---

extensions/wrapper/wrapper-ee-api/build.gradle.kts
extensions/wrapper/wrapper-ee-api/src/main/java/de/sovity/edc/ext/wrapper/api/ee/EnterpriseEditionResource.java

- add missing jakarta annotation to bind a URI parameter to a generated resource parameter
- add dependency: org.glassfish.jersey.media:jersey-media-multipart to use the anotation @DFormDataParam which binds the named body parts of a "multipart/form-data request entity body to a resource method parameter.
- cleanup swagger annotation to improve readability

Fix EE API Endpoint Definitions for File Storage

---

extensions/wrapper/wrapper-ee-api/src/main/java/de/sovity/edc/ext/wrapper/api/ee/EnterpriseEditionResource.java

Removed 'uploadStoredFile' endpoint from EE Wrapper API

Delete EE uploadFile Endpoint Definition from Wrapper API

---

.env
extensions/postgres-flyway/src/main/java/de/sovity/edc/extension/postgresql/migration/DatabaseMigrationManager.java
extensions/postgres-flyway/src/main/resources/migration/default/V2__Delete-Transfer-Processes-Trigger.sql

- dev-docker-compose with reduced number of kept transfer-processes. transfer-processes were removed from both edcs.
-   closes #439

fix: auto delete old transfer-processes if their count exceeds a certain limit

---

extensions/wrapper/client/src/test/java/de/sovity/edc/client/ContractDefinitionPageApiServiceTest.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/ContractDefinitionEntry.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/ContractDefinitionRequest.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/contracts/ContractDefinitionApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/contracts/services/ContractDefinitionBuilder.java

related to https://github.com/sovity/edc-ui/issues/332

Add ID schema field to Contract Definition

---

extensions/wrapper/client/src/test/java/de/sovity/edc/client/GetTransferProcessAssetApiServiceTest.java
extensions/wrapper/client/src/test/java/de/sovity/edc/client/TransferProcessTestUtils.java
extensions/wrapper/wrapper-common-api/src/main/java/de/sovity/edc/ext/wrapper/api/common/model/UiAsset.java
extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/UiAssetMapper.java
extensions/wrapper/wrapper-common-mappers/src/test/java/de/sovity/edc/ext/wrapper/api/common/mappers/AssetMapperTest.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtensionContextBuilder.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/transferhistory/TransferHistoryPageApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/transferhistory/TransferHistoryPageAssetFetcherService.java
utils/json-and-jsonld-utils/src/main/java/de/sovity/edc/utils/jsonld/vocab/Prop.java

updates and closes https://github.com/sovity/edc-ui/issues/262

chore: Update TransferHistory UiAsset

---

docs/deployment-guide/goals/production/README.md

Closes #636 
Since the migration from MS8 to EDC v0.x.y, there is no longer a Clearing-House connection with the current sovity EDC CE (currently v6.0.0). The setting can be removed from the documentation.

docs: remove EDC_CLEARINGHOUSE_LOG_URL from production deployment-guide

---

CHANGELOG.md
extensions/policy-referring-connector/build.gradle.kts
extensions/policy-referring-connector/src/main/java/de/sovity/edc/extension/policy/ReferringConnectorValidationExtension.java

fix: Connector-Restricted-Usage Policy #727

---

.env
.github/ISSUE_TEMPLATE/release.md
CHANGELOG.md

EDC extentions 7.2.1 release preparation for [issue 813](https://github.com/sovity/edc-extensions/issues/813)

Release 7.2.1 preparation PR

---

.github/ISSUE_TEMPLATE/release.md

Improves the releasing checklist
During release 7.2.1

Release process improvements

---

extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/UiAssetMapper.java
tests/src/test/java/de/sovity/edc/e2e/DataSourceParameterizationTest.java

Performance issue after adding new tests.
```[tasklist]
```

Fix test performance

---

CHANGELOG.md
extensions/database-direct-access/src/main/java/de/sovity/edc/extension/db/directaccess/DatabaseDirectAccessExtension.java

Fix a problem when starting the EDC without the max connection pool size property.
The timeout property doesn't need to be exposed to sysadmins.
```[tasklist]
```

fix: Pool size must be optional

---

docs/api/sovity-edc-api-wrapper.yaml
extensions/catalog-crawler/catalog-crawler-e2e-test/src/test/java/de/sovity/edc/ext/catalog/crawler/CrawlerE2eTest.java
extensions/contract-termination/src/test/java/de/sovity/edc/extension/contacttermination/query/ContractAgreementTerminationDetailsQueryTest.java
extensions/contract-termination/src/test/java/de/sovity/edc/extension/contacttermination/query/TerminateContractQueryTest.java
tests/src/test/java/de/sovity/edc/e2e/AlwaysTrueMigrationReversedTest.java
tests/src/test/java/de/sovity/edc/e2e/AlwaysTrueMigrationTest.java
tests/src/test/java/de/sovity/edc/e2e/ContractTerminationTest.java
tests/src/test/java/de/sovity/edc/e2e/DataSourceParameterizationTest.java
tests/src/test/java/de/sovity/edc/e2e/DataSourceQueryParamsTest.java
tests/src/test/java/de/sovity/edc/e2e/ManagementApiTransferTest.java
tests/src/test/java/de/sovity/edc/e2e/PlaceholderDataSourceExtensionTest.java
tests/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java
tests/src/test/java/de/sovity/edc/e2e/UseCaseApiWrapperTest.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/db/EdcRuntimeExtensionFixed.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/CeE2eTestExtensionConfigFactory.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/E2eTestExtension.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/E2eTestExtensionConfig.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/E2eTestExtensionConfigFactory.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/Helpers.java

Preparation for
https://github.com/sovity/PMO-Software/issues/1381 
```[tasklist]
```

chore: Rework E2E test extension to be used in the EDC EE

---

.env
CHANGELOG.md

https://github.com/sovity/edc-ce/issues/1017
```[tasklist]
```

chore: Release 10.1.0

---

CHANGELOG.md
extensions/postgres-flyway/src/main/resources/db/migration/V12__DROP_duplicate_indices.sql

These indices are 100% the same as the PK ones and only cause overhead, hence the removal.
```[tasklist]
```

fix: Remove duplicate database indices

---

CHANGELOG.md
docs/api/sovity-edc-api-wrapper.yaml
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/asset/AssetApiService.java
tests/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/E2eScenario.java

https://github.com/sovity/edc-ce/issues/1018
```[tasklist]
```

fix: Address update

---

docs/api/postman_collection.json

Postman-Collection contains outdated API-Wrapper Assets PUT call.
Before v9.0.0 **with** /metadata for PUT:
https://github.com/sovity/edc-ce/blob/f91a9ce14a30b0e947c0aa988db84d615a944dae/extensions/wrapper/wrapper-api/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java#L73
Including and after v9.0.0 **without** /metadata for PUT:
https://github.com/sovity/edc-ce/blob/329bfc4d4d15665a6228ce1c2fe7c29e70c81f5e/extensions/wrapper/wrapper-api/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java#L76
Release v9.0.0: https://github.com/sovity/edc-ce/releases/tag/v9.0.0
```[tasklist]
```

fix(postman): update collection to reflect recent API changes

---

.github/markdown-link-checker-config.jq
CHANGELOG.md
docs/api/postman_collection.json
extensions/wrapper/wrapper-api/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java

https://github.com/sovity/edc-ce/issues/1041
```[tasklist]
```

chore: Prepare release 10.4.0

---

.env
CHANGELOG.md

https://github.com/sovity/edc-ce/issues/1058
```[tasklist]
```

chore: Release prep v10.4.2

---

.github/workflows/license_scan.yml
.github/workflows/secret_scan.yml
.github/workflows/security_scan.yml
.github/workflows/trivy.yml

Trivy can run into db-download-rate limits using GitHub as DB host. A newer version now introduced db-caching and additionally a mirror of the original Trivy DBs is used instead of GitHub if running into GitHub rate limits.
```[tasklist]
```

fix(trivy): prevent rate-limit issues

---

CHANGELOG.md
extensions/dataset-bugfix/build.gradle.kts
extensions/dataset-bugfix/src/main/java/org/eclipse/tractusx/edc/dataset/fix/DatasetFixExtension.java
extensions/dataset-bugfix/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/sovity-edc-extensions-package/build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
tests/src/test/java/de/sovity/edc/e2e/DatasetTest.java

Closes #1065 
```[tasklist]
```

fix: Only return `Datasets` with valid `Offers`

---

.env
CHANGELOG.md
docs/api/sovity-edc-api-wrapper.yaml
tests/src/test/java/de/sovity/edc/e2e/DatasetTest.java

Related release: #1106 
```[tasklist]
```

chore: release prep 10.5.0

---

.github/workflows/ci.yml
CHANGELOG.md
extensions/wrapper/clients/benchmark/build.gradle.kts
extensions/wrapper/clients/java-client-example/src/test/java/de/sovity/edc/client/examples/Benchmark.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtensionContextBuilder.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResourceImpl.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/asset/AssetApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/contract_agreements/services/ContractAgreementDataFetcher.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/contract_definitions/ContractDefinitionApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/dashboard/DashboardPageApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/dashboard/services/DashboardDataFetcher.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/data_offer/DataOfferPageApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/policy/PolicyDefinitionApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/transferhistory/TransferHistoryPageApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/usecase/UseCaseResourceImpl.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/usecase/services/KpiApiService.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/utils/FetchBatch.java
extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/utils/QueryUtils.java
extensions/wrapper/wrapper/src/test/java/de/sovity/edc/ext/wrapper/Benchmark.java
settings.gradle.kts
tests/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java
tests/src/test/java/de/sovity/edc/ext/wrapper/api/ui/pages/dashboard/DashboardPageApiServiceTest.java
utils/catalog-parser/src/main/java/de/sovity/edc/utils/catalog/DspCatalogService.java
utils/catalog-parser/src/test/java/de/sovity/edc/utils/catalog/DspCatalogServiceTest.java
utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/junit/TestDatabaseExtension.java

Fixes asset counting in dashboard.
https://github.com/sovity/PMO-Software/issues/2066
```[tasklist]
```

fix: Fetch in batches instead of using Query.max()

---

docs/Backend/Postman/setting-up-postman.md

Older core-edc 0.2.1-based EDC also requires an older collection.

docs: update postman link of old docu to older collection
