sovity/edc-ce

build.gradle.kts, extensions/catalog-transfer-extension/build.gradle.kts, extensions/event-asset-provider/build.gradle.kts, gradle.properties, settings.gradle.kts
Modifies gradle files to publish the extension jars
=> Publish Maven Artifacts for Extensions

.github/workflows/gradle-publish.yml, extensions/catalog-transfer-extension/build.gradle.kts
Committing a version tag triggers the pipeline to publish the artifacts. 
I've tested this with a fork.
- closes https://github.com/sovity/edc-broker-extension/issues/3
=> Feat: pipeline publishes artifacts

README.md, resources/docs/get_client.sh
This PR adds a script that can be used to generate the ski/aki and jks file given a p12 keystore.
I tested the script with a provided keystore.
- closes https://github.com/sovity/edc-broker-extension/issues/10
=> feat: add ski aki extraction script

CHANGELOG.md, extensions/catalog-transfer-extension/src/main/java/sender/RegisterConnectorRequestSender.java, gradle.properties
This PR prepares the release of version 1.0.1
=> Prepare release 1.0.1

build.gradle.kts
Fixes the gradle uri for the new repo name
=> Fix: uri to publish gradle artifacts

resources/docs/docker-compose.yml
=> chore: update docker-compose to use correct registry

CHANGELOG.md, extensions/catalog-transfer-extension/src/main/java/catalogtransfer/CatalogTransferExtension.java, extensions/catalog-transfer-extension/src/main/java/sender/RegisterConnectorRequestSender.java
This PR adds the description field to the broker message. 
I've tested this with the run configuration.
- Closes https://github.com/sovity/edc-extensions/issues/9
=> Feat: add connector description to broker message

extensions/policy-referringConnector/build.gradle.kts, extensions/policy-referringConnector/src/main/java/de/sovity/edc/extension/policy/ReferringConnectorValidationExtension.java, extensions/policy-referringConnector/src/main/java/de/sovity/edc/extension/policy/functions/AbstractReferringConnectorValidation.java, extensions/policy-referringConnector/src/main/java/de/sovity/edc/extension/policy/functions/ReferringConnectorDutyFunction.java, extensions/policy-referringConnector/src/main/java/de/sovity/edc/extension/policy/functions/ReferringConnectorPermissionFunction.java, extensions/policy-referringConnector/src/main/java/de/sovity/edc/extension/policy/functions/ReferringConnectorProhibitionFunction.java, extensions/policy-referringConnector/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/policy-referringConnector/src/test/java/de/sovity/edc/extension/policy/ReferringConnectorValidationExtensionTest.java, extensions/policy-referringConnector/src/test/java/de/sovity/edc/extension/policy/functions/AbstractReferringConnectorValidationTest.java, extensions/policy-timeinterval/build.gradle.kts, extensions/policy-timeinterval/src/main/java/de/sovity/edc/extension/policy/PolicyFunctionsExtension.java, extensions/policy-timeinterval/src/main/java/de/sovity/edc/extension/policy/TimeIntervalFunction.java, extensions/policy-timeinterval/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, settings.gradle.kts
Adding EDC-Policies for time-interval and participant related rules.
- closes #15
=> feat: Publish EDC-Policies

.github/dependabot.yml
Fix docker path for dependabot scanning
=> fix docker path in dependabot.yml

.github/workflows/trivy.yml, connector/Dockerfile
Adds trivy as static analysis tool for _security-checks: vuln,secret,config_ and fixes Dockerfile user is root user.
=> chore: create trivy.yml

README.md
Fixes readme
- fixes https://github.com/sovity/edc-extensions/issues/19
=> docs: update README to remove manual generation of SKI/AKI

CHANGELOG.md, connector/build.gradle.kts
Adding policies to the connector
- fixes #44
=> feat: Adding the policies the connector

.github/workflows/docker-image.yml, .github/workflows/gradle-publish.yml, .github/workflows/secret_scan.yml, .github/workflows/trivy.yml
Adds a timeout to the actions.
=> feat: add timeout-minutes to actions

.github/workflows/gradle-publish.yml, gradle.properties
Automatically building SNAPSHOT versions for extension jars
- fixes #51
=> feat: Automatically building SNAPSHOT versions for extension jars

extensions/broker/build.gradle.kts
Publishing the broker-extension as jar
- fixes #53
=> fix: Publishing the broker-extension as jar #53

connector/build.gradle.kts
Removes the workaround to remove the IDS token validation.
=> fix: remove workaround

CHANGELOG.md, gradle.properties
Prepares the release of the next version.
=> chore: prepare release

README.md, extensions/broker/README.md, extensions/clearinghouse/README.md
Updates the readmes to the latest version.
=> docs: update readme

CHANGELOG.md, README.md, extensions/broker/src/main/java/de/sovity/extension/broker/BrokerExtension.java, extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java
This PR adds the functionality to blacklist policies from broker, meaning that assets that contain such a policy won't be pubslihed.
Locally with the run configuration and test broker.
Closes https://github.com/sovity/PMO-Software/issues/87
=> feat: blacklist policies from broker

CHANGELOG.md
Missing changelog entry for https://github.com/sovity/edc-extensions/pull/68
=> docs: add missing changelog

extensions/clearinghouse/README.md
Adds logging events to CH readme.
=> docs: add logging events to CH readme

extensions/contract-agreement-transfer-api/build.gradle.kts
Publishing the ContractAgreementTransferApiExtension as jar
=> feat: Publishing the ContractAgreementTransferApiExtension as jar

.github/workflows/docker-image.yml, connector/Dockerfile, connector/build.gradle.kts
Adapt the github actions and project setup to publish two new docker-images:
- edc: A development edc-image with reduced setup
- edc-mds:latest: The mds-image containing all required extensions
-   closes #78
=> feat: Publishing a Connector-Development-Image

extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferApiController.java, extensions/contract-agreement-transfer-api/src/test/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferApiControllerIntegrationTest.java
Prepend /contract-agreements-transfer to rest-endpoint of ContractAgreementTransferApiExtension
=> fix: Prepend /contract-agreements-transfer to rest-endpoint of ContractAgreementTransferApiExtension

gradle.properties
=> chore: Adapt version to SNAPSHOT

resources/docs/postman_collection.json
=> docs: updated postman_collection.json

extensions/policy-always-true/src/main/java/de/sovity/edc/extension/policy/AlwaysTruePolicyExtension.java
=> fix policy definition being created before extensions are ready

README.md
Adds a keystore FAQ to the README.
Closes #106
=> docs: add keystore FAQ to README.md

CHANGELOG.md
=> chore update CHANGELOG.md

.github/workflows/gradle-publish.yml
Fixes https://github.com/sovity/edc-extensions/issues/115
=> chore: fix path

build.gradle.kts, extensions/last-commit-info/src/test/java/de/sovity/edc/extension/version/controller/LastCommitInfoEnvTest.java, extensions/last-commit-info/src/test/java/de/sovity/edc/extension/version/controller/LastCommitInfoJarTest.java
Ensures that tests are run for all sub-projects.
=> fix: gradle not finding tests #127

extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java
This PR adds more exception catching. In the future this can be extended to allow for a more precise error handling. 
Fixes https://github.com/sovity/edc-extensions/issues/105
=> chore: catch remaining possible exceptions

extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java
Fixes possible NullPointer in IdsBrokerServiceImpl.
Closes #136
=> fix: possible NullPointer in IdsBrokerServiceImpl

README.md
Adds a disclaimer to README.md.
=> docs: add disclaimer to README.md

CHANGELOG.md, docker-compose.yaml
=> fix: Cannot fetch own catalog due to wrong port mapping

connector/build.gradle.kts
Adds the **integrated** data-plane to the project.
=> feat: enhance data-plane in project

README.md
=> docs: add FAQ to README.md

CHANGELOG.md, gradle.properties
=> release: v1.3.0

README.md, docker-compose.yaml
Rearranged docker-compose  to simplify finding variables, which need to be changed.
=> Rearrange docker-compose variables

CHANGELOG.md, gradle.properties
=> release: 1.4.0

resources/docs/openapi.yaml
Adds the OpenAPI-Specification to the resources/docs folder. The Specification has been generated from the `v0.0.1-milestone-8` tag of the core-EDC repository.
=> docs: Add OpenAPI specification for milestone-8 EDC #152

docker-compose.yaml
Sets the EDC_UI_DATA_MANAGEMENT_API_URL to the management context
=> fix: set EDC_UI_DATA_MANAGEMENT_API_URL

docker-compose-dev.yaml
Adds a second EDC Connector, EDC Connector UI and DB.
=> chore: add second edc, edc-ui and db to docker-compose-dev

CHANGELOG.md, docker-compose.yaml, gradle.properties
=> chore: prepare release 2.0.1

CHANGELOG.md, extensions/postgres-flyway/src/main/resources/migration/contractnegotiation/V0_0_3__Fix_Contract_Offer_JSON.sql
fix contract negotiation JSON field conctract offers not migrated, missing contractStart, contractEnd
=> 2023 03 22 fix migrations 2

resources/docs/EDC-Http-Pull.postman_collection.json, resources/docs/sovity-EDC.postman_collection.json
Simplifies Postman Collection with a focus on the most important APIs.
=> chore: clean up postman collection

CHANGELOG.md, docker-compose.yaml, gradle.properties
=> chore: prepare release 2.0.3

CHANGELOG.md, gradle.properties
=> chore: prepare next release

CHANGELOG.md, extensions/wrapper/client-example/build.gradle.kts, extensions/wrapper/client/build.gradle.kts, extensions/wrapper/wrapper/build.gradle.kts
Summary of dependabot updates.
=> chore: summary of dependabot updates

CHANGELOG.md, extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java
=> feat: re-register assets at broker

docker-compose.yaml
Fixes issues in docker-compose after restructuring the repo.
=> fix: docker-compose.yaml

CHANGELOG.md, README.md, connector/README.md, connector/build.gradle.kts, docker-compose.yaml, docs/getting-started/README.md, extensions/contract-agreement-transfer-api/README.md, extensions/edc-ui-config/README.md, extensions/ids-broker-client/README.md, extensions/ids-clearinghouse-client/README.md, extensions/last-commit-info/README.md, extensions/policy-always-true/README.md, extensions/policy-referring-connector/README.md, extensions/policy-time-interval/README.md, extensions/postgres-flyway/README.md, extensions/sovity-edc-extensions-package/README.md, extensions/wrapper/README.md, extensions/wrapper/client-example/README.md, extensions/wrapper/client-ts/README.md, extensions/wrapper/client/README.md, extensions/wrapper/wrapper/README.md
=> Fix readmes

.github/workflows/build-and-publish-connector-images.yml, connector/Dockerfile, docker-compose-dev.yaml, docker-compose.yaml, docs/getting-started/secrets/example-fs-vault.properties
it doesn't belong in the dev edition
=> fix docker compose filesystem vault

extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/usecase/ContractAgreementPageService.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/usecase/model/AssetDto.java
=> feat: add more asset information

.env, CHANGELOG.md, gradle.properties
=> chore: prepare release 3.1.0

CHANGELOG.md, gradle.properties
=> chore: prepare next version

extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/ContractAgreementCard.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/services/ContractAgreementPageCardBuilder.java, extensions/wrapper/wrapper/src/test/java/de/sovity/edc/ext/wrapper/api/ui/ContractAgreementPageTest.java
=> feat add contract negotiation id (contract agreement page)

STYLEGUIDE.md
=> docs: add STYLEGUIDE.md

extensions/policy-referring-connector/src/main/java/de/sovity/edc/extension/policy/ReferringConnectorValidationExtension.java
=> feat: Register referringConnector policy under a second name

build.gradle.kts, connector/build.gradle.kts, extensions/contract-agreement-transfer-api/build.gradle.kts, extensions/edc-ui-config/build.gradle.kts, extensions/ids-broker-client/build.gradle.kts, extensions/ids-clearinghouse-client/build.gradle.kts, extensions/last-commit-info/build.gradle.kts, extensions/policy-always-true/build.gradle.kts, extensions/policy-referring-connector/build.gradle.kts, extensions/policy-time-interval/build.gradle.kts, extensions/postgres-flyway/build.gradle.kts, extensions/sovity-edc-extensions-package/build.gradle.kts, extensions/wrapper/client/build.gradle.kts, extensions/wrapper/wrapper-broker-api/build.gradle.kts, extensions/wrapper/wrapper-common-api/build.gradle.kts, extensions/wrapper/wrapper-ee-api/build.gradle.kts, extensions/wrapper/wrapper/build.gradle.kts, gradle.properties
fixes gradle module group names
=> fix group names

.github/workflows/build-and-publish-connector-images.yml, README.md, connector/README.md, docker-compose-dev.yaml, docker-compose.yaml, docs/getting-started/README.md, extensions/ids-broker-client/README.md, extensions/ids-clearinghouse-client/README.md, extensions/postgres-flyway/README.md, extensions/sovity-edc-extensions-package/README.md, extensions/wrapper/README.md, extensions/wrapper/client-example/README.md, extensions/wrapper/client-ts-example/README.md, extensions/wrapper/client-ts/README.md, extensions/wrapper/client/README.md, extensions/wrapper/wrapper-broker-api/README.md, extensions/wrapper/wrapper-common-api/README.md, extensions/wrapper/wrapper-ee-api/README.md, extensions/wrapper/wrapper-ee-api/src/main/java/de/sovity/edc/ext/wrapper/api/ee/EnterpriseEditionResource.java, extensions/wrapper/wrapper/README.md
closes https://github.com/sovity/edc-extensions/issues/335
=> rename product to "sovity Community/Enterprise Edition EDC"

.env, .github/ISSUE_TEMPLATE/release.md, CHANGELOG.md, docker-compose.yaml
related to #369 
post man collection changes not done yet
=> chore: prepare release 3.3.0

docker-compose.yaml, extensions/ids-broker-client/src/main/java/de/sovity/extension/broker/BrokerExtension.java, extensions/ids-clearinghouse-client/src/main/java/de/sovity/extension/clearinghouse/ClearingHouseExtension.java
=> feat: turn broker- and clearinghouse client off

extensions/wrapper/wrapper-broker-api/build.gradle.kts, extensions/wrapper/wrapper-common-api/build.gradle.kts, extensions/wrapper/wrapper-ee-api/build.gradle.kts, extensions/wrapper/wrapper/build.gradle.kts
=> deps: dependabot updates

docs/getting-started/documentation/pull-data-transfer.md
Adds documentation for http-pull-transfer with a dynamically set pull-backend url
=> doc: Add documentation for http-pull-transfer with a dynamically set pull-backend url

.env, CHANGELOG.md, docker-compose.yaml
=> Prep release 400

CHANGELOG.md, extensions/policy-referring-connector/src/main/java/de/sovity/edc/extension/policy/ReferringConnectorValidationExtension.java, extensions/policy-referring-connector/src/main/java/de/sovity/edc/extension/policy/functions/AbstractReferringConnectorValidation.java, extensions/policy-referring-connector/src/test/java/de/sovity/edc/extension/policy/functions/AbstractReferringConnectorValidationTest.java
Closes #422 
ReferringConnectorValidationExtension: Added support for comma separated lists of connectors using the EQ operator as well as pure Lists using the IN operator. (see tests for functionality)
=> feat(ConnectorRestrictedPolicy): Accepting list of connectors and IN

extensions/wrapper/wrapper-ee-api/src/main/java/de/sovity/edc/ext/wrapper/api/ee/EnterpriseEditionResourceImpl.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtensionContextBuilder.java
=> feat: register basic implementation for EnterpriseEditionResource

connector/Dockerfile
=> fix: improve docker image security

connector/Dockerfile
=> fix: alpine image not including bash

.env, CHANGELOG.md, docker-compose-dev.yaml, gradle.properties
=> release: v4.1.0 #454

gradle.properties
=> chore: prepare next release #454

.github/ISSUE_TEMPLATE/release.md
=> chore: improve release template

connector/build.gradle.kts
=> fix: remove clearing house and broker extensions from mds variant build

.github/workflows/ci.yml, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/UiCriterionDto.java
related to https://github.com/sovity/edc-ui/issues/332
=> fix: UICriterionDto Nullability

docs/getting-started/documentation/oauth-data-address.md
Add documentation for connector usage of OAuth2 protected APIs
-   closes #494
=> doc: connector usage for oauth protected APIs #494

extensions/wrapper/client/src/test/java/de/sovity/edc/client/PolicyDefinitionApiServiceTest.java, extensions/wrapper/wrapper-common-api/src/main/java/de/sovity/edc/ext/wrapper/api/common/model/PolicyDefinitionCreateRequest.java, extensions/wrapper/wrapper-common-api/src/main/java/de/sovity/edc/ext/wrapper/api/common/model/PolicyDefinitionDto.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/PolicyMapper.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/PolicyDefinitionPage.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/policy/PolicyDefinitionApiService.java
Related to https://github.com/sovity/edc-ui/issues/330
=> Fix for Policy Naming

launchers/connectors/sovity-dev/src/test/java/de/sovity/edc/e2e/ConnectorTransferTest.java, utils/test-connector-remote/src/main/java/de/sovity/edc/extension/e2e/connector/config/ConnectorConfig.java, utils/test-connector-remote/src/main/java/de/sovity/edc/extension/e2e/connector/config/api/EdcApiGroupConfig.java
=> feat: enable setting the authProvider for a ConnectorConfig

extensions/postgres-flyway/src/main/resources/migration/default/V3__MS8-to-0.2.1.sql, extensions/wrapper/wrapper-common-api/src/main/java/de/sovity/edc/ext/wrapper/api/common/model/UiAssetCreateRequest.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/JsonBuilderUtils.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/UiAssetMapper.java, extensions/wrapper/wrapper-common-mappers/src/test/java/de/sovity/edc/ext/wrapper/api/common/mappers/AssetMapperTest.java, extensions/wrapper/wrapper-common-mappers/src/test/resources/example-asset.jsonld, launchers/connectors/sovity-dev/src/test/java/de/sovity/edc/e2e/Ms8ConnectorTransferTest.java, launchers/connectors/sovity-dev/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java, launchers/connectors/sovity-dev/src/test/resources/db/additional-test-data/provider/V1_9__ms8-test-contract-provider.sql, utils/json-and-jsonld-utils/build.gradle.kts, utils/json-and-jsonld-utils/src/main/java/de/sovity/edc/utils/JsonUtils.java, utils/json-and-jsonld-utils/src/main/java/de/sovity/edc/utils/jsonld/JsonLdUtils.java, utils/json-and-jsonld-utils/src/main/java/de/sovity/edc/utils/jsonld/vocab/Prop.java
depends on https://github.com/sovity/edc-extensions/pull/537
closes https://github.com/sovity/edc-extensions/issues/426
=> Additional Asset Properties

utils/test-connector-remote/src/main/java/de/sovity/edc/extension/e2e/connector/ConnectorRemote.java
=> feat: increase ConnectorRemote timeouts #562

CHANGELOG.md, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/AssetMapper.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/AssetJsonLdUtils.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/AtomicConstraintMapper.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/ConstraintExtractor.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/FailedMappingException.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/JsonBuilderUtils.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/LiteralMapper.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/MappingErrors.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/PolicyValidator.java, extensions/wrapper/wrapper-common-mappers/src/main/java/de/sovity/edc/ext/wrapper/api/common/mappers/utils/UiAssetMapper.java, extensions/wrapper/wrapper-common-mappers/src/test/java/de/sovity/edc/ext/wrapper/api/common/mappers/AssetMapperTest.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtension.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtensionContextBuilder.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/catalog/CatalogApiService.java, utils/catalog-parser/src/main/java/de/sovity/edc/utils/catalog/DspCatalogService.java, utils/catalog-parser/src/main/java/de/sovity/edc/utils/catalog/mapper/DspDataOfferBuilder.java, utils/catalog-parser/src/main/java/de/sovity/edc/utils/catalog/model/DspCatalog.java, utils/catalog-parser/src/test/java/de/sovity/edc/utils/catalog/DspCatalogServiceTest.java
Improved common mappers for broker
=> chore: Change fetchDataOffers

.github/ISSUE_TEMPLATE/MDS_feature_request.md
_Briefly describe WHAT your PR changes, which features it adds/modifies._
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
-   Test A
-   Test B
-   ...
**Test Configuration**:
-   Firmware version:
-   Hardware:
-   Toolchain:
-   SDK:
_Use keywords to automate: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword_
-   fixes # (issue)
-   closes # (issue)
-   ...
-   [ ] blocked by # (issue)
-   [ ] I have **formatted the title** correctly and precisely
-   [ ] My code follows the **style guidelines** of this project
-   [ ] I have performed a **self-review** of my own …
=> chore: Uploaded a raw template file to further build template

CHANGELOG.md, docs/getting-started/documentation/pull-data-transfer.md
https://github.com/sovity/edc-extensions/issues/728
```[tasklist]
```
=> doc: Enhance HTTP-Pull Documentation

.github/workflows/license_scan.yml
Updates the configuration of the license scanning.
```[tasklist]
```
=> ci: update license scanning

docs/deployment-guide/goals/production/4.2.0/README.md, docs/deployment-guide/goals/production/README.md
An extra section on security-related topics will be added to the documentation.
=> docs: add security recommendations

.github/workflows/ci.yml, tests/src/test/java/de/sovity/edc/e2e/ApiWrapperDemoTest.java, tests/src/test/java/de/sovity/edc/e2e/ManagementApiTransferTest.java, tests/src/test/java/de/sovity/edc/e2e/Ms8ConnectorMigrationTest.java, tests/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java
https://github.com/sovity/PMO-Software/issues/584
```[tasklist]
```
=> feat: remove the github postgres service and use Testcontainers

extensions/wrapper/wrapper-common-mappers/src/test/java/de/sovity/edc/ext/wrapper/api/common/mappers/AssetMapperTest.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/asset/AssetBuilder.java, extensions/wrapper/wrapper/src/test/java/de/sovity/edc/ext/wrapper/api/ui/pages/asset/AssetApiServiceTest.java
=> fix: add new fields to buildCreateRequest

.env, CHANGELOG.md, docker-compose-dev.yaml
Prepare Release 7.3.0: https://github.com/sovity/edc-extensions/issues/867
```[tasklist]
```
=> release: prepare release 7.3.0

.github/workflows/ci.yml, CHANGELOG.md, build.gradle.kts, docs/deployment-guide/goals/production/README.md, launchers/common/base-mds/build.gradle.kts
Adds the Logging House Extension 0.2.10.
=> feat: add logging-house-client

.env, CHANGELOG.md
https://github.com/sovity/edc-extensions/issues/879
```[tasklist]
```
=> Release 7.4.0 preparation

.github/workflows/ci.yml, CHANGELOG.md, extensions/postgres-flyway/src/main/resources/migration/default/V6__ChangeDistributionField.sql, extensions/wrapper/wrapper-common-mappers/src/test/resources/example-asset.jsonld, utils/json-and-jsonld-utils/src/main/java/de/sovity/edc/utils/jsonld/vocab/Prop.java
=> fix: try fix Distribution field error

.github/ISSUE_TEMPLATE/release.md
=> docs: update release issue

.env, CHANGELOG.md, tests/src/test/java/de/sovity/edc/e2e/UseCaseApiWrapperTest.java
https://github.com/sovity/edc-extensions/issues/924
```[tasklist]
```
=> Release prep 7.5.0

.github/ISSUE_TEMPLATE/release.md, .github/workflows/check_docs.yml, .github/workflows/ci.yml
=> Update releasing procedure

.github/ISSUE_TEMPLATE/release.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, CHANGELOG.md, build.gradle.kts, docs/api/postman_collection.json
- Revised Postman collection with API-Wrapper API-calls and more Management-API API-calls.
- Process improvements to keep the Postman-Collection up to date in the future.
```[tasklist]
```
New structure as of now:
=> docs: expand postman-collection

.env, .github/ISSUE_TEMPLATE/release.md, CHANGELOG.md, archived/broker/README.md, docker-compose-dev.yaml, docker-compose.yaml
Release praparation
```[tasklist]
```
=> chore: Release preparation v8.0.0

.github/ISSUE_TEMPLATE/release.md
Post release procedure update
```[tasklist]
```
=> chore: Update release procedure

CHANGELOG.md
Improve releasing notes
```[tasklist]
```
=> Indicate Broker version

.env, CHANGELOG.md
Closes #973 
```[tasklist]
```
=> release: 8.1.0

docs/api/postman_collection.json
Closes #975 
```[tasklist]
```
=> feat: Add policy-definition Endpoint of Use-Case-Api to Postman

CHANGELOG.md, docs/api/postman_collection.json, docs/api/sovity-edc-api-wrapper.yaml, extensions/wrapper/wrapper-api/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtensionContextBuilder.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResourceImpl.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/contract_agreements/ContractAgreementPageApiService.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/contract_agreements/services/ContractAgreementDataFetcher.java, tests/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java, utils/test-utils/src/main/java/de/sovity/edc/extension/e2e/extension/E2eScenario.java
=> feat: fetch a single contract agreement by its ID

docs/getting-started/documentation/faq.md
Adds a FAQ section to the Community Edition. 
```[tasklist]
```
=> docs: add faq.md

docs/api/postman_collection.json
Closes https://github.com/sovity/edc-ce/issues/1033
```[tasklist]
```
=> docs: add on-request data-source as example in asset-creation

.env, CHANGELOG.md
https://github.com/sovity/edc-ce/issues/1036
```[tasklist]
```
=> chore: Release prep 10.3.0

.env
https://github.com/sovity/edc-ce/issues/1041
```[tasklist]
```
=> fix: Also add .env changes

CHANGELOG.md, extensions/catalog-crawler/catalog-crawler-db/src/main/resources/db-crawler/migration/V11__Connector_registration_enhancements.sql
=> AP Flyway Migration Sync

CHANGELOG.md, extensions/catalog-crawler/catalog-crawler-db/src/main/resources/db-crawler/migration/V11__Connector_registration_enhancements.sql
This reverts commit a02b631ea9a04a0e256ded2e4448e7ebf6effbdb.
Relates to https://github.com/sovity/edc-ce/issues/1047
```[tasklist]
```
=> chore: Revert "chore: ap flyway migration sync (#1045)"

.env, CHANGELOG.md
https://github.com/sovity/edc-ce/issues/1047
```[tasklist]
```
=> Release 10.4.1

.github/workflows/ci.yml, .github/workflows/license_scan.yml, .github/workflows/secret_scan.yml, .github/workflows/security_scan.yml, .github/workflows/trivy.yml, CHANGELOG.md, docs/api/sovity-edc-api-wrapper.yaml, extensions/wrapper/wrapper-api/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/DataOfferCreationRequest.java, extensions/wrapper/wrapper-api/src/main/java/de/sovity/edc/ext/wrapper/api/ui/model/PolicyDefinitionChoiceEnum.java, extensions/wrapper/wrapper/build.gradle.kts, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtension.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/WrapperExtensionContextBuilder.java, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/data_offer/DataOfferPageApiService.java, tests/src/test/java/de/sovity/edc/e2e/UiApiWrapperTest.java
Picked the parts that are wanted for the next release
```[tasklist]
```
=> chore: cherry-pick elements for a hotfix release

docs/Backend/API-Wrapper/OpenAPI/assets.md
I noticed that the endpoint was missing.
Assuming the endpoint would be `POST pages/asset-page/assets`, I made the changed accordingly
=> Added Asset creation endpoint

.env, .github/workflows/ci.yml, CHANGELOG.md
=> chore: ci for prs against mds/main

CHANGELOG.md, extensions/catalog-crawler/catalog-crawler-db/src/main/resources/db-crawler/migration/V12__Fix_Service_Provider_User_Deletion.sql
=> chore: release prep 10.4.4

.github/DISCUSSION_TEMPLATE/general.yml, .github/DISCUSSION_TEMPLATE/ideas.yml, .github/DISCUSSION_TEMPLATE/q-a.yml
=> Discusssion Templates

CHANGELOG.md, extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/utils/QueryUtils.java
https://github.com/sovity/edc-ee/issues/1096
=> fix: Remove the "ALL" log line
